[
    {
        "filter": "ent",
        "latencyCount": 20,
        "profile": "Enterprise All",
        "shortName": "All"
    },
    {
        "filter": "ent+all+watchlist",
        "latencyCount": 20,
        "profile": "Enterprise All - Watchlist",
        "shortName": "All - Watchlist"
    },
    {
        "filter": "ent+all+linux",
        "latencyCount": 15,
        "profile": "Enterprise All (Linux)",
        "shortName": "All (L)"
    },
    {
        "filter": "ent+all+windows",
        "latencyCount": 15,
        "profile": "Enterprise All (Windows)",
        "shortName": "All (W)"
    },
    {
        "filter": "ent+latin america",
        "latencyCount": 15,
        "profile": "Enterprise Latin America",
        "shortName": "LATAM"
    },
    {
        "filter": "ent+east",
        "latencyCount": 15,
        "profile": "Enterprise East",
        "shortName": "East"
    },
    {
        "filter": "ent+east+linux",
        "latencyCount": 15,
        "profile": "Enterprise East (Linux)",
        "shortName": "East (L)"
    },
    {
        "filter": "ent+east+windows",
        "latencyCount": 15,
        "profile": "Enterprise East (Windows)",
        "shortName": "East (W)"
    },
    {
        "filter": "ent+west",
        "latencyCount": 15,
        "profile": "Enterprise West",
        "shortName": "West"
    },
    {
        "filter": "ent+west+linux",
        "latencyCount": 15,
        "profile": "Enterprise West (Linux)",
        "shortName": "West (L)"
    },
    {
        "filter": "ent+west+windows",
        "latencyCount": 15,
        "profile": "Enterprise West (Windows)",
        "shortName": "West (W)"
    },
    {
        "filter": "ent+f1k",
        "latencyCount": 15,
        "profile": "Enterprise F1000",
        "shortName": "F1000"
    },
    {
        "filter": "ent+f1k+linux",
        "latencyCount": 15,
        "profile": "Enterprise F1000 (Linux)",
        "shortName": "F1000 (L)"
    },
    {
        "filter": "ent+f1k+windows",
        "latencyCount": 15,
        "profile": "Enterprise F1000 (Windows)",
        "shortName": "F1000 (W)"
    },
    {
        "filter": "ent+n+linux",
        "latencyCount": 10,
        "profile": "Team N",
        "shortName": "N"
    },
    {
        "filter": "ent+o+linux",
        "latencyCount": 10,
        "profile": "Team O",
        "shortName": "O"
    },
    {
        "filter": "ent+p+linux",
        "latencyCount": 10,
        "profile": "Team P",
        "shortName": "P"
    },
    {
        "filter": "ent+q+windows",
        "latencyCount": 10,
        "profile": "Team Q",
        "shortName": "Q"
    },
    {
        "filter": "ent+r+windows",
        "latencyCount": 10,
        "profile": "Team R",
        "shortName": "R"
    },
    {
        "filter": "ent+s+windows",
        "latencyCount": 10,
        "profile": "Team S",
        "shortName": "S"
    },
    {
        "filter": "ent+t+windows",
        "latencyCount": 10,
        "profile": "Team T",
        "shortName": "T"
    },
    {
        "filter": "ent+u+windows",
        "latencyCount": 10,
        "profile": "Team U",
        "shortName": "U"
    },
    {
        "filter": "ent+u+windows",
        "latencyCount": 10,
        "profile": "Team U - Windows",
        "shortName": "U - W"
    },
    {
        "filter": "ent+u+linux",
        "latencyCount": 10,
        "profile": "Team U - Linux",
        "shortName": "U - L"
    },
    {
        "filter": "ent+v+linux",
        "latencyCount": 10,
        "profile": "Team V",
        "shortName": "V"
    },
    {
        "filter": "ent+w+windows",
        "latencyCount": 10,
        "profile": "Team W",
        "shortName": "W"
    },
    {
        "filter": "ent+x+linux",
        "latencyCount": 10,
        "profile": "Team X",
        "shortName": "X"
    },
    {
        "filter": "cloud",
        "latencyCount": 10,
        "profile": "Enterprise Cloud Only",
        "shortName": "Cloud "
    },
    {
        "filter": "aric",
        "latencyCount": 1,
        "profile": "Enterprise ARIC Only",
        "shortName": "ARIC "
    },
    {
        "filter": "cas",
        "latencyCount": 15,
        "profile": "Critical Sites",
        "shortName": "CAS"
    },
    {
        "filter": "ent+netsec",
        "latencyCount": 15,
        "profile": "Enterprise NetSec",
        "shortName": "NetSec"
    },
    {
        "filter": "mbu+mbur",
        "latencyCount": 15,
        "profile": "Backup",
        "shortName": "MBU"
    }
]
